POST http://localhost:3000/api/users
Content-Type: application/json; charset=UTF-8

{
    "offset": 0,
    "limit": 3,
    "query": {
        "userId": "12345",
        "userName" : "test taro"
    }
}